export const userInputs = [
  {
    id: 1,
    key: "username",
    label: "Username",
    type: "text",
    placeholder: "john_doe",
  },
  {
    id: 2,
    key: "fullname",
    label: "Name and surname",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: 3,
    key: "email",
    label: "Email",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: 4,
    key: "phoneNumber",
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
  },
  {
    id: 5,
    key: "password",
    label: "Password",
    type: "password",
  },
  {
    id: 6,
    key: "address",
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    id: 7,
    label: "Country",
    type: "text",
    placeholder: "USA",
  },
];

export const productInputs = [
  {
    id: 1,
    label: "Title",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: 2,
    label: "Description",
    type: "text",
    placeholder: "Description",
  },
  {
    id: 3,
    label: "Category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: 4,
    label: "Price",
    type: "text",
    placeholder: "100",
  },
  {
    id: 5,
    label: "Stock",
    type: "text",
    placeholder: "in stock",
  },
];

export const hotelInputs = [
  {
    id: "name",
    key: "name",
    label: "Name",
    type: "text",
    placeholder: "My Hotel",
  },
  {
    id: "type",
    key: "typeId",
    label: "Type",
    type: "number",
    placeholder: "hotel",
  },
  {
    id: "city",
    key: "cityId",
    label: "City",
    type: "number",
    placeholder: "New York",
  },
  {
    id: "address",
    key: "address",
    label: "Address",
    type: "text",
    placeholder: "elton st, 216",
  },
  {
    id: "distance",
    key: "distance",
    label: "Distance",
    type: "text",
    placeholder: "500",
  },
  {
    id: "title",
    label: "Title",
    type: "text",
    placeholder: "The best Hotel",
  },
  {
    id: "desc",
    key: "description",
    label: "Description",
    type: "text",
    placeholder: "description",
  },
  {
    id: "shortDesc",
    key: "shortDescription",
    label: "Features",
    type: "text",
    placeholder: "Features",
  },
  {
    id: "cheapestPrice",
    key: "price",
    label: "Price",
    type: "number",
    placeholder: "100",
  },
  {
    id: "numberOfKids",
    key: "numberOfKids",
    label: "Number of kids",
    type: "number",
    placeholder: "0",
  },
  {
    id: "numberOfAdults",
    key: "numberOfAdults",
    label: "Number of adults",
    type: "number",
    placeholder: "1",
  },
  {
    id: "numberOfRooms",
    key: "numberOfRooms",
    label: "Number of rooms",
    type: "number",
    placeholder: "1",
  },
];
